name: Build and Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Install packages
        run: npm install

      - name: Configure basePath
        run:
          "sed -i 's/basePath: \x27\x27/basePath: \x27${{ github.event.repository.name }}\x27/g' next.config.mjs"

      - name: Print config
        run: "cat next.config.mjs"

      - name: Build
        run: npm run build

      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: out/

  deploy:
    needs: build
    
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4