name: Build and Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Install packages
        run: npm install

      - name: Build
        run: npm run build
        env:
          GHREPO: ${{ github.event.repository.name }}

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Build snippets
        run: dotnet build public/snippets/forms_example_1

      - name: Move snippet and it's artifacts to the out directory
        run: |
          cp -r public/snippets/forms_example_1/wwwroot/* out/snippets/forms_example_1/
          mkdir out/snippets/forms_example_1/code
          cp public/snippets/forms_example_1/Client.fs out/snippets/forms_example_1/code/Client.fs
          cp public/snippets/forms_example_1/wwwroot/index.html out/snippets/forms_example_1/code/index.html

      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: out/

  deploy:
    needs: build
    
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
